title: CV | Adilet Begimkanov
description:  in code we trust.
url: https://xeofus.com
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
